version: '3'
services:
  db:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: n1md4
      MYSQL_USER: app
      MYSQL_PASSWORD: app@2018
      MYSQL_DATABASE: log_analyzer
      MYSQL_ROOT_HOST: '%'
    volumes:
      - C:/var/lib/mysql:/var/lib/mysql
      - ./database:/data/application
    networks:
      - loganalyzer_cluster

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - loganalyzer_cluster

#  loganalizer:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: ["./wait-for-it.sh", "db:3306"]
#    ports:
#      - "9000:9000"
#    networks:
#      - loganalyzer_cluster

networks:
  loganalyzer_cluster:
    driver: bridge