server:
  port: 9000

hikari:
  datasource:
    poolName: WebServerLogAnalyzerConnectionPool
    jdbcUrl: jdbc:mysql://db:3306/log_analyzer?rewriteBatchedStatements=true
    username: app
    password: app@2018
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 3
    autoCommit: false

logging.level:
  com.zaxxer.hikari.HikariConfig: DEBUG