server:
  port: 9000

hikari:
  datasource:
    poolName: WebServerLogAnalyzerConnectionPool
    jdbcUrl: jdbc:mysql://localhost:3306/log_analyzer
    username: app
    password: app@2018
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 3

spring:
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.batch_size: 10000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true


#logging.level:
#  com.zaxxer.hikari.HikariConfig: DEBUG
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type.descriptor.sql.BasicBinder: TRACE